// Original Korean scripts. Each episode has one editorial learning objective.
// Age bands and durations are product choices, not clinical recommendations.
const scene=(text,visual)=>({text,visual,targetSeconds:15});
export const episodes=[
 {id:'story_cloud',title:'구름아, 내 마음을 들어줘',series:'마음 날씨 숲',minAgeMonths:24,maxAgeMonths:35,theme:'내 마음을 말로 표현하기',parentPrompt:'아이의 표정을 따라 해 보고, 지금 마음을 한 단어로 이야기해 보세요. 대답을 재촉하지 않아도 괜찮아요.',palette:'warm sage green, butter yellow, soft cream, daylight',scenes:[
 scene('모모가 나뭇잎을 쌓아요. 하나 올리고, 또 올리고. 작은 잎사귀 집이에요. 모모가 방긋 웃어요. 기분이 좋아요.', 'Momo the green bird stacks a little leaf house on a flat mossy stone. Close view of the delicate leaves and proud smile. Duri and Nuri are not present.'),
 scene('살랑! 바람이 불었어요. 잎사귀 집이 팔랑팔랑. 앗, 납작해졌네! 모모의 웃음도 쏙 들어갔어요.', 'A soft breeze scatters the tiny leaf house. Leaves flutter down safely. Momo opens its eyes in surprise and its smile fades. No storm.'),
 scene('모모가 고개를 푹 숙여요. 날개도 축 처졌어요. 마음이 어떤 걸까요? 잠깐, 모모의 얼굴을 볼까요?', 'Quiet close shot of Momo with drooping wings beside the fallen leaves. Subtle blinking and breathing. Gentle sad expression, not crying intensely. Leave time to observe the face.'),
 scene('구름 친구 누리가 왔어요. 모모야, 무슨 일이야? 모모는 대답 대신, 흩어진 잎사귀를 가리켰어요.', 'Nuri the small white cloud friend walks in and gently crouches beside Momo. Momo points with a wing at the scattered leaf house. Nuri listens attentively.'),
 scene('누리가 가만히 기다려요. 모모가 작은 목소리로 말했어요. 내 집이 무너져서, 속상해. 누리가 고개를 끄덕여요.', 'Two-shot of the friends at eye level. Momo touches its chest then indicates the leaves with a subdued expression. Nuri gives a slow sympathetic nod. Soft breeze in background.'),
 scene('속상했구나. 열심히 만들었는데. 누리는 모모 옆에 앉았어요. 모모는 아직 속상해요. 그래도 혼자는 아니에요.', 'Nuri sits quietly close to Momo without forcing a smile or hug. Momo remains a little sad, shoulders relaxing. A comforting still woodland moment with living background.'),
 scene('그때, 잎사귀 하나가 누리 머리에 착! 누리가 눈을 위로 굴려요. 어라? 내 머리에 누가 앉았지?', 'A single golden leaf lands on Nuri curly head. Nuri looks upward with a funny curious expression and gently pats its head but misses the leaf. Momo notices.'),
 scene('모모가 피식 웃어요. 잎사귀 모자야! 누리가 살짝 인사해요. 안녕하세요, 모자 구름입니다. 모모가 또 웃어요.', 'Nuri makes a tiny theatrical bow wearing the leaf as a hat. Momo giggles and its wings bounce softly. Comical but calm animation, no exaggerated camera.'),
 scene('모모가 말했어요. 누리야, 나랑 다시 만들래? 이번에는 작은 집으로. 누리가 대답해요. 응, 같이 해 보자.', 'Momo gestures invitingly toward a sheltered place beside a root. Nuri nods. They select a few broad leaves, planning a much smaller house.'),
 scene('작은 잎 하나, 큰 잎 하나. 모모가 올리고, 누리가 잡아요. 삐뚤빼뚤해도 괜찮아요. 둘이 만든 집이에요.', 'The two friends build a low two-leaf tent protected by a broad tree root. Nuri holds one leaf while Momo leans the other against it. The small tent stays upright.'),
 scene('모모가 가슴에 날개를 얹어요. 아까는 속상했어. 지금은 조금 좋아. 누리가 웃어요. 말해 줘서 고마워.', 'Warm close-up of Momo touching its chest, looking back at the fallen leaves then at the newly built tiny shelter. Nuri listens warmly. Small contented smile, no magical transformation.'),
 scene('우리 친구 마음은 지금 어떨까요? 좋아요? 속상해요? 곁에 있는 어른에게 말해 봐도 좋아요. 모모와 누리도, 안녕!', 'The leaf house stays in foreground. Momo and Nuri turn gently toward the audience and wave once, then settle together watching the leaves. Peaceful conclusive wide shot.')
 ]},
 {id:'story_swing',title:'그네 하나, 친구 셋',series:'우당탕 친구들',minAgeMonths:36,maxAgeMonths:71,theme:'차례를 정하고 기다리기',parentPrompt:'집에 있는 장난감 하나로 차례를 바꿔 보세요. 기다리는 동안 무엇을 하고 싶은지도 함께 정해 보세요.',palette:'warm honey sunlight, moss green, coral flowers',scenes:[
 scene('숲에 새 그네가 생겼어요. 튼튼한 나무 아래, 낮고 작은 그네예요. 모모와 두리, 누리가 눈을 반짝였어요.', 'Establishing shot of one low sturdy wooden swing in the same forest clearing. Momo, Duri and Nuri approach from a path, curious and delighted. Swing is stationary.'),
 scene('내가 먼저! 나도 타고 싶어! 세 친구가 동시에 말했어요. 그네는 하나인데, 타고 싶은 친구는 셋이에요.', 'The three friends each raise a wing or paw eagerly near the single empty swing, stopping at a safe distance. Friendly overlapping gestures, no pushing or crowding onto seat.'),
 scene('두리가 그네를 바라봐요. 셋이 모두 앉을 수 있을까? 작은 자리에 엉덩이를 대어 보려다, 멈췄어요. 너무 좁네.', 'Duri measures the small empty swing seat with its paws and looks at the three friends. They remain on ground. Clearly one rider only; nobody climbs or jumps.'),
 scene('모모가 날개를 번쩍 들어요. 목소리가 제일 큰 친구부터? 두리는 입을 열었다가 닫았어요. 누리는 뒤로 쏙 숨었어요.', 'Momo eagerly raises a wing suggesting an idea. Duri starts to respond then hesitates. Nuri quietly hides partly behind Duri. Small emotional close-ups, no yelling.'),
 scene('모모가 누리를 봤어요. 누리야, 너도 타고 싶어? 누리가 끄덕여요. 응. 나는 큰 소리가 잘 안 나와.', 'Momo turns toward shy Nuri and lowers itself to Nuri eye level. Nuri comes out from behind Duri and quietly nods toward the swing. Duri listens.'),
 scene('모모가 날개를 내렸어요. 큰 소리 말고, 차례를 정하자. 누리가 말해요. 먼저 온 두리, 그다음 모모, 그다음 나.', 'Friends sit on a mossy bench well outside swing path. Nuri points gently to Duri, Momo, then itself. All nod to agree on a sequence.'),
 scene('두리가 물었어요. 그럼 우리 모두 탈 수 있겠네? 모모가 고개를 끄덕여요. 응! 조금씩 타고, 다음 친구에게 바꿔 주자.', 'Momo holds up a golden leaf and proposes an idea. Duri and Nuri listen with interested expressions beside the still swing.'),
 scene('친구들이 함께 약속해요. 한 친구가 타고, 다른 친구는 밖에서 기다리기. 차례를 바꿀 때는 그네를 멈추고 내려오기.', 'Wide clear staging shows the low swing with Duri seated holding both ropes and the other two friends waiting on a bench outside the swing arc. Swing moves only slightly.'),
 scene('두리 차례예요. 앞으로 살랑, 뒤로 살랑. 두리 귀도 살랑살랑. 모모와 누리가 그네 바깥에서 함께 웃어요.', 'Duri enjoys a very gentle low swing while seated holding ropes. Momo and Nuri smile on distant bench. Ears softly bounce, subtle humorous joy, no high swinging.'),
 scene('모모는 발을 꼼지락거려요. 나도 빨리 타고 싶은데. 누리가 물어요. 기다리면서, 나뭇잎 모자를 만들어 볼까?', 'Close shot on waiting bench. Momo impatiently wiggles orange toes, then looks at Nuri offering a broad leaf as a silly hat. Swing remains safely distant.'),
 scene('누리가 작은 잎을 머리에 올려요. 그런데 잎이 툭, 코로 내려왔어요. 에취! 모모가 웃어요. 코 모자가 됐네!', 'Nuri leaf hat slides down over its face, landing on its little nose area, then flutters away with a tiny sneeze. Momo giggles. No explosive sneeze or rapid cuts.'),
 scene('두리는 조금 더 타고 싶었어요. 그네 줄을 꼭 잡고, 친구들을 바라봐요. 모모도 기다리고 있네. 두리가 천천히 멈췄어요.', 'Duri gently stops its low swing with feet on ground and looks wistfully at friends. Hands stay on ropes until fully still. Quiet moment of deciding to hand over.'),
 scene('두리가 말해요. 아쉽지만, 이제 모모 차례지. 그네가 멈추자 내려왔어요. 모모가 대답해요. 기다려 줘서 고마워.', 'Stationary low swing: Duri steps off safely to side, Momo approaches only after it is empty. They exchange warm smiles and a small wave.'),
 scene('모모가 앉았어요. 작고 동그란 몸이 살랑살랑. 두리는 기다리는 자리에 앉아요. 아까는 나, 지금은 모모 차례예요.', 'Momo sits centered on low swing holding both ropes with wings. Tiny gentle motion. Duri sits beside Nuri on bench outside swing path. Establish clear spatial arrangement.'),
 scene('두리도 발을 꼼지락거려요. 누리가 잎사귀 모자를 내밀어요. 두리가 쓰자, 귀 한쪽만 쏙 덮였어요. 귀 모자네!', 'On waiting bench Nuri puts the little leaf hat on Duri, but it covers only one rounded ear. Duri points to its funny ear hat and both laugh softly.'),
 scene('잠시 뒤, 모모가 그네를 멈췄어요. 누리야, 네 차례야. 누리가 방긋 웃어요. 작은 목소리로도, 내 차례가 왔네.', 'Momo fully stops and leaves the swing. Nuri joyfully approaches the empty seat. Momo invites Nuri with open wing. No simultaneous riders.'),
 scene('누리는 아주 살짝만 흔들고 싶대요. 모모와 두리가 고개를 끄덕여요. 누리의 그네는 구름처럼, 천천히 움직여요.', 'Nuri sits securely on low swing with hands on ropes, rocking very slowly through a tiny arc. Momo and Duri watch supportively from bench. Gentle cloudlike movement.'),
 scene('두리가 그네 앞으로 가려다 멈춰요. 아, 여기서 기다리기로 했지. 두리는 모모 옆에 앉아, 누리에게 손을 흔들어요.', 'Duri takes a small step from the distant bench, remembers the waiting place and sits back beside Momo. Nuri remains safely far away on swing. Wave of encouragement.'),
 scene('세 친구 모두 그네를 탔어요. 기다릴 때는 조금 아쉬웠지만, 내 차례도 왔어요. 다음에도 이 약속으로 놀자!', 'All three friends gather beside the now empty stationary swing, smiling and acknowledging each other. Duri passes the funny leaf hat to Nuri. Warm evening light.'),
 scene('우리도 장난감 하나로 차례를 바꿔 볼까요? 기다리는 동안 무엇을 할까요? 모모와 두리, 누리가 인사해요. 다음에 만나!', 'Conclusive wide shot. The three friends sit together on mossy bench and wave gently to audience, with low stationary swing to side. Camera slowly eases back into forest.')
 ]},
 {id:'story_moon',title:'사라진 달빛을 찾아서',series:'꼬마 숲 탐정',minAgeMonths:72,maxAgeMonths:95,theme:'생각한 것을 관찰로 확인하기',parentPrompt:'밝은 곳에서 물그릇에 비친 물체를 함께 관찰해 보세요. 물이 움직일 때와 멈출 때 무엇이 달라지는지 이야기해 보세요.',palette:'gentle indigo twilight, teal foliage, silver moonlight, warm firefly accents, no scary darkness',scenes:[
 scene('해가 지고, 달이 떠올랐어요. 모모와 두리는 넓고 마른 길에서 연못을 바라봐요. 물 위에도 동그란 달이 보였어요.', 'Peaceful dusk, a full moon in sky and its clear reflection on still small pond. Momo and Duri stand well back on a broad dry path. Soft bright twilight, no scary darkness.'),
 scene('두리가 속삭여요. 하늘에 하나, 연못에 하나. 달이 둘일까? 모모가 고개를 갸웃해요. 가까이 살펴보자. 길 위에서!', 'Two friends look up at full moon then toward its reflection from safe dry path. Duri points up then down, puzzled. Momo tilts its head, keeping a clear distance from bank.'),
 scene('그때, 바람이 살랑 불었어요. 물결이 찰랑찰랑. 동그란 달이 길게 늘어나더니, 반짝이는 조각처럼 흩어졌어요.', 'Close view of pond surface as a mild breeze creates ripples. Round full moon reflection stretches into shimmering broken highlights. Moon itself remains round in sky, no literal fragments.'),
 scene('두리가 눈을 동그랗게 떠요. 어? 연못의 달이 없어졌어! 모모가 말해요. 정말 없어진 걸까? 무엇이 달라졌지?', 'From safe path Duri shows curious surprise, not fear, pointing at shimmering pond. Momo notices the moving reeds. Full moon visible above. Gentle observational atmosphere.'),
 scene('두리는 큰 잎사귀를 발견했어요. 저 잎이 달을 덮었나 봐! 모모는 바로 고개를 끄덕이지 않았어요. 한번 확인해 보자.', 'A broad floating leaf near one side of pond catches Duri attention. Momo gestures to observe carefully. Keep floating leaf and disturbed moon reflection spatially distinct.'),
 scene('바람이 잎사귀를 옆으로 밀었어요. 그런데 달은 아직 조각조각 반짝여요. 두리가 말해요. 잎 때문만은 아니었네.', 'The floating leaf drifts slowly away from reflected moon area while water stays rippled and reflection stays broken. Friends watch attentively from path, no water contact.'),
 scene('모모가 하늘을 올려다봤어요. 하늘의 달은 여전히 동그래요. 두리도 봤어요. 하늘의 달은 사라지지 않았구나.', 'Camera tilts gently from friends looking up to a clear full moon in twilight sky, then holds. Show unchanged round moon, no fantasy face or smile on moon.'),
 scene('모모가 작은 갈대를 가리켜요. 갈대도 흔들리고, 물도 흔들려. 두리가 생각해요. 혹시, 물이 움직여서 그런 걸까?', 'Foreground reeds sway in mild breeze, visible ripples cross pond. Momo points to reed then water, Duri thoughtfully touches chin. Same warm childlike characters.'),
 scene('둘은 서두르지 않고 기다렸어요. 바람이 약해지자, 갈대가 멈췄어요. 물결도 조금씩, 조금씩 잦아들어요.', 'Single patient shot of reeds gradually stilling and small ripples subsiding on pond. Friends sit on a dry wooden bench well away from edge and quietly observe.'),
 scene('어라! 물 위의 달이 다시 동그래졌어요. 두리가 손뼉을 작게 쳐요. 돌아왔네! 물이 잔잔해지니까 잘 보여.', 'The moon reflection reforms into a recognizable round bright disk on now calm pond. Duri gives one small delighted clap. Full moon still in sky. Natural reflection, no magic.'),
 scene('모모가 말해요. 한 번 더 보고 싶어. 마침 바람이 다시 살랑 불었어요. 물 위의 동그라미가 또 흔들려요.', 'A second gentle breeze returns, rippling water and distorting reflection again. Momo and Duri deliberately watch the change from same safe viewpoint.'),
 scene('두리가 천천히 말해요. 물이 흔들리면 달빛도 흔들려 보여. 물이 멈추면 동그랗게 보여. 두 번 모두 그랬어.', 'Balanced composition showing rippled moon reflection settling gradually into round reflection. Duri traces a little wave gesture then circle gesture with paws while Momo watches.'),
 scene('누리가 길을 따라 왔어요. 무엇을 보고 있어? 두리가 말해요. 연못의 달! 처음에는 잎사귀가 가린 줄 알았어.', 'Nuri joins friends by walking along broad dry path, not across water. Duri gestures toward floating leaf and pond to share discovery. Friendly greeting in bright twilight.'),
 scene('누리가 물어요. 그런데 어떻게 알았어? 모모가 대답해요. 잎이 옆으로 가도 흔들렸어. 그래서 다른 것을 살펴봤지.', 'Three friends converse on path. Momo points toward leaf resting at pond margin then waving reeds. Nuri follows the directions with curious eyes. No text or diagrams.'),
 scene('두리가 덧붙여요. 바람이 멈출 때, 다시 불 때, 물 위의 모습이 달라졌어. 생각만 하지 않고, 직접 봤어.', 'Duri demonstrates gentle wavy paw motion while pond behind shows light breeze. Nuri nods in understanding. Calm explanatory character animation, no classroom writing.'),
 scene('누리가 하늘과 연못을 번갈아 봐요. 물에 보이는 건 달이 비친 모습이구나. 진짜 달은, 저 하늘에 있어.', 'Wide composition clearly shows one full moon in sky and its corresponding reflection in pond beneath. Nuri points up, then to reflected image. All stay on safe path.'),
 scene('그때 누리의 얼굴도 물에 살짝 비쳤어요. 바람이 불자 볼이 길쭉길쭉! 두리가 웃어요. 누리 얼굴도 춤추네!', 'View from dry path of Nuri reflected near pond edge at an angle, without leaning over water. A mild ripple playfully distorts reflection. Real Nuri keeps normal shape. Gentle humor.'),
 scene('누리는 볼을 만져 봤어요. 내 얼굴은 그대로인데? 모모가 웃어요. 물에 비친 모습이 흔들린 거야. 세 친구가 웃어요.', 'Close shot Nuri gently pats round cheeks, puzzled then amused. Momo and Duri chuckle. Pond reflection glimmers behind them, bright comforting twilight.'),
 scene('처음 생각이 달라도 괜찮아요. 자세히 보고, 다시 확인하면 새로운 걸 알 수 있어요. 오늘의 달빛 탐정들처럼요.', 'The friends quietly admire calm pond from bench, a sense of discovery and conclusion. Floating leaf rests to side, moon reflection clear. Slow cinematic pullback.'),
 scene('다음에는 어른과 함께, 물그릇에 비친 모습을 살펴볼까요? 물이 움직이면 어떻게 될까요? 달빛 탐정들의 오늘 이야기는 여기까지. 안녕!', 'Final wide forest tableau with Momo Duri Nuri waving once from dry path and then walking calmly toward a warmly lit forest home, pond and full moon behind. Peaceful complete ending.')
 ]}
];
